"""initial

Revision ID: 451732b7e3da
Revises: None
Create Date: 2014-08-07 12:41:52.043636

"""

# revision identifiers, used by Alembic.
revision = '451732b7e3da'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('in_use', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('loo_id', sa.Integer(), nullable=True),
    sa.Column('in_use', sa.Boolean(), nullable=True),
    sa.Column('seconds_in_state', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['loo_id'], ['loos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('loos')
    ### end Alembic commands ###
